---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b     # frozen: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 8d1b9cadaf854cb25bb0b0f5870e1cc66a083d6b     # frozen: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --width=120
          - --offset=2
          - --sequence=4


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea        # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: .*\.md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 7bcc70ca475b87e0fdee2511300c74b25babe0b3   # frozen: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pappasam/toml-sort
    rev: b9b6210da457c38122995e434b314f4c4a4a923e   # frozen: v0.23.1
    hooks:
      - id: toml-sort-fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 8cd2d4056637e242709fe09f15a36f0b4b682bda   # frozen: v1.8.0
    hooks:
      - id: mypy
        verbose: true
        exclude: ^.*_gunicorn_config\.py$
        additional_dependencies:
          - types-redis
          - litestar[standard, pydantic, sqlalchemy]
          - pydantic-settings
          - git+https://github.com/andrewasheridan/exemplars.git@main
