---
version: '3.9'
services:
    postgres:
        image: postgres:latest
        volumes:
          - postgres:/var/lib/postrgresql/data/
        expose:
          - 5432:5432
        env_file:
          - .env
        healthcheck:
            test: [CMD-SHELL, pg_isready -d postgres -U postgres]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 3s
        networks:
          - default


    vinculum:
        build:
            context: .
            args:
                INSTALL_DEPENDENCIES: dev
        depends_on:
            postgres:
                condition: service_healthy
        ports:
          - 8001:8001
        env_file:
          - .env
        volumes:
          - .:/app:cached
        networks:
          - default
          - mynetwork

volumes:
    postgres: {}
networks:
    mynetwork:
        name: mynetwork
