"""first

Revision ID: a03ac4a1ad5d
Revises: 
Create Date: 2024-01-01 17:17:37.521737

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "a03ac4a1ad5d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
